### ISSUE TITLE
Malformed agent response causes `KeyError` in `check_response`

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/sorunlib#174]
The response from a misbehaving agent might not contain `op_name`, which causes the following error:
```
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/usr/local/lib/python3.10/dist-packages/sorunlib/smurf.py", line 271, in zero_biases
    _run_op('zero_biases',
  File "/usr/local/lib/python3.10/dist-packages/sorunlib/smurf.py", line 85, in _run_op
    check_response(smurf, resp)
  File "/usr/local/lib/python3.10/dist-packages/sorunlib/_internal.py", line 45, in check_response
    op = response.session['op_name']
KeyError: 'op_name'
```

This was observed at site on satp3 with a pysmurf-controller agent trying to run `smurf.zero_biases()`. If this occurs we need to drop that controller agent like we typically do.

**sorunlib version:** 0.1.16

**Comment by jlashner** [comment]
I'm kind of surprised this is possible, were there any interesting logs in the pysmurf-controller?
